theme: jekyll-theme-midnight

title: Hello, it's nice to meet you ;)
description: If I had to choose a word to describe myself, it would be curiosity. I want to know more; more about the world, more about myself, more about what makes things work the way they do. 
